import 'package:flutter/material.dart';

enum CaptionPosition { top, center, bottom }

enum CaptionEffect {
  none,
  pop,
  fade,
  karaoke,
  bounce,
  typewriter,
  slideUp,
  stagger,
  pulse,
  drift,
}

extension CaptionEffectDetails on CaptionEffect {
  String get title => switch (this) {
    CaptionEffect.none => 'Clean',
    CaptionEffect.pop => 'Pop',
    CaptionEffect.fade => 'Fade',
    CaptionEffect.karaoke => 'Karaoke',
    CaptionEffect.bounce => 'Bounce',
    CaptionEffect.typewriter => 'Typewriter',
    CaptionEffect.slideUp => 'Slide Up',
    CaptionEffect.stagger => 'Stagger',
    CaptionEffect.pulse => 'Pulse',
    CaptionEffect.drift => 'Drift',
  };

  String get description => switch (this) {
    CaptionEffect.none => 'Stable and distraction-free',
    CaptionEffect.pop => 'Words punch in with energy',
    CaptionEffect.fade => 'Soft, smooth word transitions',
    CaptionEffect.karaoke => 'Highlights each spoken word',
    CaptionEffect.bounce => 'Playful bounce on every beat',
    CaptionEffect.typewriter => 'Reveals text like a typewriter',
    CaptionEffect.slideUp => 'Words rise into position',
    CaptionEffect.stagger => 'Words arrive one after another',
    CaptionEffect.pulse => 'Gentle scale pulse for emphasis',
    CaptionEffect.drift => 'Light movement with a floating feel',
  };

  String get sample => switch (this) {
    CaptionEffect.none => 'keep it simple',
    CaptionEffect.pop => 'MAKE IT POP!',
    CaptionEffect.fade => 'softly spoken',
    CaptionEffect.karaoke => 'follow the words',
    CaptionEffect.bounce => 'feel the beat',
    CaptionEffect.typewriter => '> writing now_',
    CaptionEffect.slideUp => 'rise & shine',
    CaptionEffect.stagger => 'one word at a time',
    CaptionEffect.pulse => 'say it louder',
    CaptionEffect.drift => 'floating captions',
  };

  IconData get icon => switch (this) {
    CaptionEffect.none => Icons.remove_circle_outline_rounded,
    CaptionEffect.pop => Icons.bolt_rounded,
    CaptionEffect.fade => Icons.blur_on_rounded,
    CaptionEffect.karaoke => Icons.highlight_rounded,
    CaptionEffect.bounce => Icons.sports_basketball_rounded,
    CaptionEffect.typewriter => Icons.keyboard_alt_outlined,
    CaptionEffect.slideUp => Icons.keyboard_arrow_up_rounded,
    CaptionEffect.stagger => Icons.view_agenda_outlined,
    CaptionEffect.pulse => Icons.favorite_border_rounded,
    CaptionEffect.drift => Icons.air_rounded,
  };

  Color get accent => switch (this) {
    CaptionEffect.none => const Color(0xFFB7C0C2),
    CaptionEffect.pop => const Color(0xFFFF805C),
    CaptionEffect.fade => const Color(0xFFD9C7FF),
    CaptionEffect.karaoke => const Color(0xFFFFD15C),
    CaptionEffect.bounce => const Color(0xFFFF6B4A),
    CaptionEffect.typewriter => const Color(0xFF9FE870),
    CaptionEffect.slideUp => const Color(0xFF8EC5FF),
    CaptionEffect.stagger => const Color(0xFFFFB86B),
    CaptionEffect.pulse => const Color(0xFFC6FF3D),
    CaptionEffect.drift => const Color(0xFF6BE7FF),
  };
}

enum CaptionLayout { inline, ladder, hierarchy }

enum CaptionFont {
  manrope,
  poppins,
  inter,
  anton,
  syne,
  dmSans,
  jetBrainsMono,
  baloo2,
  montserrat,
  playfair,
  caveat,
  permanentMarker,
  bungee,
  spaceGrotesk,
  pixel,
  abril,
  lobster,
  oswald,
  righteous,
  archivoBlack,
  rubikMono,
  chivo,
  comfortaa,
  cormorant,
  fredoka,
  leagueGothic,
  lilitaOne,
  pacifico,
  ptSansNarrow,
  rubikWetPaint,
  rye,
  secularOne,
  staatliches,
  truculenta,
  tiltWarp,
  sriracha,
}

class CaptionDesign {
  const CaptionDesign({
    this.size = 27,
    this.position = CaptionPosition.center,
    this.color = Colors.white,
    this.activeColor = const Color(0xFFC96442),
    this.weight = FontWeight.w800,
    this.visible = true,
    this.effect = CaptionEffect.none,
    this.font = CaptionFont.manrope,
    this.backgroundColor,
    this.borderColor,
    this.boxHorizontalPadding = 0,
    this.boxVerticalPadding = 0,
    this.boxRadius = 0,
    this.letterSpacing = 0,
    this.outlineWidth = 1.5,
    this.maxWordsPerLine = 4,
    this.uppercase = false,
    this.glow = false,
    this.layout = CaptionLayout.inline,
    this.doubleLayer = false,
    this.wordChip = false,
    this.chipColor = const Color(0xE6111115),
    this.hardShadow = false,
  });
  final double size;
  final CaptionPosition position;
  final Color color;
  final Color activeColor;
  final FontWeight weight;
  final bool visible;
  final CaptionEffect effect;
  final CaptionFont font;
  final Color? backgroundColor;
  final Color? borderColor;
  final double boxHorizontalPadding;
  final double boxVerticalPadding;
  final double boxRadius;
  final double letterSpacing;
  final double outlineWidth;
  final int maxWordsPerLine;
  final bool uppercase;
  final bool glow;
  final CaptionLayout layout;
  final bool doubleLayer;
  final bool wordChip;
  final Color chipColor;
  final bool hardShadow;

  CaptionDesign copyWith({
    double? size,
    CaptionPosition? position,
    Color? color,
    Color? activeColor,
    FontWeight? weight,
    bool? visible,
    CaptionEffect? effect,
    CaptionFont? font,
    Color? backgroundColor,
    Color? borderColor,
    double? boxHorizontalPadding,
    double? boxVerticalPadding,
    double? boxRadius,
    double? letterSpacing,
    double? outlineWidth,
    int? maxWordsPerLine,
    bool? uppercase,
    bool? glow,
    CaptionLayout? layout,
    bool? doubleLayer,
    bool? wordChip,
    Color? chipColor,
    bool? hardShadow,
  }) => CaptionDesign(
    size: size ?? this.size,
    position: position ?? this.position,
    color: color ?? this.color,
    activeColor: activeColor ?? this.activeColor,
    weight: weight ?? this.weight,
    visible: visible ?? this.visible,
    effect: effect ?? this.effect,
    font: font ?? this.font,
    backgroundColor: backgroundColor ?? this.backgroundColor,
    borderColor: borderColor ?? this.borderColor,
    boxHorizontalPadding: boxHorizontalPadding ?? this.boxHorizontalPadding,
    boxVerticalPadding: boxVerticalPadding ?? this.boxVerticalPadding,
    boxRadius: boxRadius ?? this.boxRadius,
    letterSpacing: letterSpacing ?? this.letterSpacing,
    outlineWidth: outlineWidth ?? this.outlineWidth,
    maxWordsPerLine: maxWordsPerLine ?? this.maxWordsPerLine,
    uppercase: uppercase ?? this.uppercase,
    glow: glow ?? this.glow,
    layout: layout ?? this.layout,
    doubleLayer: doubleLayer ?? this.doubleLayer,
    wordChip: wordChip ?? this.wordChip,
    chipColor: chipColor ?? this.chipColor,
    hardShadow: hardShadow ?? this.hardShadow,
  );

  static CaptionDesign fromTemplate(String template) => switch (template) {
    'Podcast Minimal' => const CaptionDesign(
      size: 25,
      position: CaptionPosition.center,
      color: Color(0xFFF8F8F8),
      activeColor: Colors.white,
      weight: FontWeight.w700,
      effect: CaptionEffect.stagger,
      font: CaptionFont.inter,
      outlineWidth: 0,
      maxWordsPerLine: 5,
    ),
    'Emphasis Outline' => const CaptionDesign(
      size: 31,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFFFD15C),
      weight: FontWeight.w900,
      effect: CaptionEffect.stagger,
      font: CaptionFont.montserrat,
      outlineWidth: 2.5,
      maxWordsPerLine: 3,
      layout: CaptionLayout.hierarchy,
    ),
    'Clean Box' => const CaptionDesign(
      size: 27,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Colors.white,
      weight: FontWeight.w800,
      effect: CaptionEffect.fade,
      font: CaptionFont.inter,
      backgroundColor: Color(0xE9000000),
      boxHorizontalPadding: 20,
      boxVerticalPadding: 12,
      boxRadius: 16,
      outlineWidth: 0,
      maxWordsPerLine: 4,
    ),
    'Bubble' => const CaptionDesign(
      size: 25,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFFFD15C),
      weight: FontWeight.w800,
      effect: CaptionEffect.bounce,
      font: CaptionFont.dmSans,
      backgroundColor: Color(0xE9000000),
      boxHorizontalPadding: 24,
      boxVerticalPadding: 10,
      boxRadius: 999,
      outlineWidth: 0,
      maxWordsPerLine: 4,
    ),
    'Hormozi Bold' => const CaptionDesign(
      size: 34,
      position: CaptionPosition.center,
      color: Color(0xFFD4FF3D),
      activeColor: Color(0xFFFF6B4A),
      weight: FontWeight.w900,
      effect: CaptionEffect.pop,
      font: CaptionFont.montserrat,
      backgroundColor: Color(0xEC000000),
      boxHorizontalPadding: 10,
      boxVerticalPadding: 8,
      boxRadius: 5,
      outlineWidth: 0,
      maxWordsPerLine: 2,
      uppercase: true,
    ),
    'MrBeast Impact' => const CaptionDesign(
      size: 38,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFFFE45C),
      weight: FontWeight.w900,
      effect: CaptionEffect.pop,
      font: CaptionFont.anton,
      outlineWidth: 4.5,
      maxWordsPerLine: 1,
      uppercase: true,
    ),
    'Karaoke Bar' => const CaptionDesign(
      size: 27,
      position: CaptionPosition.bottom,
      color: Colors.white,
      activeColor: Color(0xFFC96442),
      weight: FontWeight.w800,
      effect: CaptionEffect.karaoke,
      font: CaptionFont.dmSans,
      backgroundColor: Color(0xE9000000),
      boxHorizontalPadding: 16,
      boxVerticalPadding: 10,
      boxRadius: 14,
      outlineWidth: 0,
      maxWordsPerLine: 4,
    ),
    'Gold Shadow' => const CaptionDesign(
      size: 30,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFE8A94C),
      weight: FontWeight.w800,
      effect: CaptionEffect.slideUp,
      font: CaptionFont.montserrat,
      outlineWidth: 0,
      maxWordsPerLine: 3,
      layout: CaptionLayout.hierarchy,
      glow: true,
    ),
    'Neon Highlight' => const CaptionDesign(
      size: 31,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFC6FF3D),
      weight: FontWeight.w900,
      effect: CaptionEffect.pulse,
      font: CaptionFont.montserrat,
      outlineWidth: 0,
      maxWordsPerLine: 3,
      layout: CaptionLayout.hierarchy,
      glow: true,
    ),
    'Double Pop' => const CaptionDesign(
      size: 33,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFFF6B4A),
      weight: FontWeight.w900,
      effect: CaptionEffect.pop,
      font: CaptionFont.montserrat,
      outlineWidth: 1.2,
      maxWordsPerLine: 3,
      doubleLayer: true,
    ),
    'Left Ladder' => const CaptionDesign(
      size: 30,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFFFD15C),
      weight: FontWeight.w900,
      effect: CaptionEffect.stagger,
      font: CaptionFont.poppins,
      outlineWidth: 2,
      maxWordsPerLine: 4,
      layout: CaptionLayout.ladder,
    ),
    'Stacked Punch' => const CaptionDesign(
      size: 33,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFFF5C5C),
      weight: FontWeight.w900,
      effect: CaptionEffect.bounce,
      font: CaptionFont.anton,
      outlineWidth: 2.5,
      maxWordsPerLine: 4,
      layout: CaptionLayout.ladder,
      uppercase: true,
    ),
    'Soft Talk' => const CaptionDesign(
      size: 24,
      position: CaptionPosition.center,
      color: Color(0xFFF7F4EE),
      activeColor: Color(0xFFFFD5A0),
      weight: FontWeight.w600,
      effect: CaptionEffect.fade,
      font: CaptionFont.manrope,
      outlineWidth: 0,
      maxWordsPerLine: 5,
    ),
    'Coral Punch' => const CaptionDesign(
      size: 32,
      position: CaptionPosition.center,
      color: Color(0xFFFF6B4A),
      activeColor: Colors.white,
      weight: FontWeight.w900,
      effect: CaptionEffect.pop,
      font: CaptionFont.syne,
      outlineWidth: 2.2,
      maxWordsPerLine: 3,
      uppercase: true,
    ),
    'Electric Wave' => const CaptionDesign(
      size: 31,
      position: CaptionPosition.center,
      color: Color(0xFF6BE7FF),
      activeColor: Color(0xFFB184FF),
      weight: FontWeight.w800,
      effect: CaptionEffect.drift,
      font: CaptionFont.syne,
      outlineWidth: 0,
      maxWordsPerLine: 3,
      glow: true,
    ),
    'Mono Signal' => const CaptionDesign(
      size: 25,
      position: CaptionPosition.center,
      color: Color(0xFFF4F4F4),
      activeColor: Color(0xFF9FE870),
      weight: FontWeight.w700,
      effect: CaptionEffect.typewriter,
      font: CaptionFont.jetBrainsMono,
      letterSpacing: .55,
      outlineWidth: 0,
      maxWordsPerLine: 4,
    ),
    'Halo Words' => const CaptionDesign(
      size: 31,
      position: CaptionPosition.center,
      color: Color(0xFFEAD7FF),
      activeColor: Colors.white,
      weight: FontWeight.w800,
      effect: CaptionEffect.pulse,
      font: CaptionFont.poppins,
      outlineWidth: 0,
      maxWordsPerLine: 3,
      glow: true,
    ),
    'Marker Pop' => const CaptionDesign(
      size: 31,
      position: CaptionPosition.center,
      color: Colors.black,
      activeColor: Colors.black,
      weight: FontWeight.w900,
      effect: CaptionEffect.pop,
      font: CaptionFont.montserrat,
      backgroundColor: Color(0xFFFFFF52),
      boxHorizontalPadding: 12,
      boxVerticalPadding: 7,
      boxRadius: 4,
      outlineWidth: 0,
      maxWordsPerLine: 3,
      uppercase: true,
    ),
    'Nightline' => const CaptionDesign(
      size: 26,
      position: CaptionPosition.bottom,
      color: Color(0xFFEAEAEA),
      activeColor: Color(0xFFB184FF),
      weight: FontWeight.w700,
      effect: CaptionEffect.slideUp,
      font: CaptionFont.manrope,
      backgroundColor: Color(0xCC171725),
      boxHorizontalPadding: 16,
      boxVerticalPadding: 9,
      boxRadius: 12,
      outlineWidth: 0,
      maxWordsPerLine: 4,
    ),
    'Retro Offset' => const CaptionDesign(
      size: 31,
      position: CaptionPosition.center,
      color: Color(0xFFFFF1CF),
      activeColor: Color(0xFFFF5C5C),
      weight: FontWeight.w900,
      effect: CaptionEffect.drift,
      font: CaptionFont.anton,
      outlineWidth: 1.5,
      maxWordsPerLine: 3,
      doubleLayer: true,
      uppercase: true,
    ),
    'Quiet Outline' => const CaptionDesign(
      size: 30,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFFFD15C),
      weight: FontWeight.w800,
      effect: CaptionEffect.fade,
      font: CaptionFont.inter,
      outlineWidth: 2.4,
      maxWordsPerLine: 4,
    ),
    'Cloud Float' => const CaptionDesign(
      size: 27,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFF8BE9FD),
      weight: FontWeight.w700,
      effect: CaptionEffect.drift,
      font: CaptionFont.dmSans,
      outlineWidth: 0,
      maxWordsPerLine: 4,
      glow: true,
    ),
    'Fire Starter' => const CaptionDesign(
      size: 34,
      position: CaptionPosition.center,
      color: Color(0xFFFFE45C),
      activeColor: Color(0xFFFF5C5C),
      weight: FontWeight.w900,
      effect: CaptionEffect.bounce,
      font: CaptionFont.anton,
      outlineWidth: 3,
      maxWordsPerLine: 2,
      uppercase: true,
    ),
    'Solar Build' => const CaptionDesign(
      size: 34,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFFFE24D),
      weight: FontWeight.w900,
      effect: CaptionEffect.stagger,
      font: CaptionFont.anton,
      outlineWidth: 1.8,
      maxWordsPerLine: 3,
      hardShadow: true,
      uppercase: true,
    ),
    'Hard Echo' => const CaptionDesign(
      size: 33,
      position: CaptionPosition.center,
      color: Color(0xFFFF655D),
      activeColor: Colors.white,
      weight: FontWeight.w900,
      effect: CaptionEffect.pop,
      font: CaptionFont.bungee,
      outlineWidth: 0,
      maxWordsPerLine: 2,
      hardShadow: true,
      doubleLayer: true,
      uppercase: true,
    ),
    'Midnight Chip' => const CaptionDesign(
      size: 26,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFFFD15C),
      weight: FontWeight.w800,
      effect: CaptionEffect.karaoke,
      font: CaptionFont.dmSans,
      maxWordsPerLine: 3,
      wordChip: true,
      chipColor: Color(0xEF101015),
    ),
    'Focus Pixel' => const CaptionDesign(
      size: 20,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFC9FF48),
      weight: FontWeight.w800,
      effect: CaptionEffect.pop,
      font: CaptionFont.pixel,
      outlineWidth: 1,
      maxWordsPerLine: 1,
      glow: true,
      uppercase: true,
    ),
    'Velvet Three' => const CaptionDesign(
      size: 34,
      position: CaptionPosition.center,
      color: Color(0xFFFFEBD2),
      activeColor: Color(0xFFE99AFF),
      weight: FontWeight.w700,
      effect: CaptionEffect.stagger,
      font: CaptionFont.playfair,
      maxWordsPerLine: 3,
      layout: CaptionLayout.hierarchy,
      glow: true,
    ),
    'Ember Karaoke' => const CaptionDesign(
      size: 28,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFFF6B4A),
      weight: FontWeight.w900,
      effect: CaptionEffect.karaoke,
      font: CaptionFont.montserrat,
      maxWordsPerLine: 3,
      wordChip: true,
      chipColor: Color(0xED251714),
      uppercase: true,
    ),
    'Prism Stack' => const CaptionDesign(
      size: 31,
      position: CaptionPosition.center,
      color: Color(0xFFBDEEFF),
      activeColor: Color(0xFFFF8CD8),
      weight: FontWeight.w800,
      effect: CaptionEffect.drift,
      font: CaptionFont.righteous,
      outlineWidth: 1.4,
      maxWordsPerLine: 4,
      layout: CaptionLayout.ladder,
      doubleLayer: true,
      glow: true,
    ),
    'Noir Plate' => const CaptionDesign(
      size: 28,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFF9FE870),
      weight: FontWeight.w800,
      effect: CaptionEffect.fade,
      font: CaptionFont.chivo,
      backgroundColor: Color(0xE9000000),
      boxHorizontalPadding: 18,
      boxVerticalPadding: 10,
      boxRadius: 3,
      maxWordsPerLine: 3,
    ),
    'Signal Tag' => const CaptionDesign(
      size: 27,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFF75EDFF),
      weight: FontWeight.w800,
      effect: CaptionEffect.slideUp,
      font: CaptionFont.spaceGrotesk,
      maxWordsPerLine: 3,
      wordChip: true,
      chipColor: Color(0xEE101D25),
    ),
    'Mint Outline' => const CaptionDesign(
      size: 33,
      position: CaptionPosition.center,
      color: Color(0xFFEFFFF2),
      activeColor: Color(0xFF7CFFB1),
      weight: FontWeight.w900,
      effect: CaptionEffect.pulse,
      font: CaptionFont.archivoBlack,
      outlineWidth: 2.8,
      maxWordsPerLine: 3,
      glow: true,
      uppercase: true,
    ),
    'Horizon Slide' => const CaptionDesign(
      size: 31,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFFFAE5D),
      weight: FontWeight.w800,
      effect: CaptionEffect.slideUp,
      font: CaptionFont.oswald,
      outlineWidth: 2,
      maxWordsPerLine: 3,
      layout: CaptionLayout.hierarchy,
      uppercase: true,
    ),
    'Paper Stamp' => const CaptionDesign(
      size: 30,
      position: CaptionPosition.center,
      color: Colors.black,
      activeColor: Color(0xFFFFCE56),
      weight: FontWeight.w900,
      effect: CaptionEffect.bounce,
      font: CaptionFont.permanentMarker,
      backgroundColor: Color(0xFFF7F0DD),
      boxHorizontalPadding: 13,
      boxVerticalPadding: 8,
      boxRadius: 5,
      maxWordsPerLine: 2,
      hardShadow: true,
      uppercase: true,
    ),
    'Cinema Serif' => const CaptionDesign(
      size: 32,
      position: CaptionPosition.center,
      color: Color(0xFFFFF4DF),
      activeColor: Color(0xFFFFC15C),
      weight: FontWeight.w700,
      effect: CaptionEffect.slideUp,
      font: CaptionFont.playfair,
      outlineWidth: 1.2,
      maxWordsPerLine: 3,
      layout: CaptionLayout.hierarchy,
      glow: true,
    ),
    'Script Bloom' => const CaptionDesign(
      size: 40,
      position: CaptionPosition.center,
      color: Color(0xFFFFF7EA),
      activeColor: Color(0xFFFF78C6),
      weight: FontWeight.w700,
      effect: CaptionEffect.drift,
      font: CaptionFont.caveat,
      outlineWidth: 1.1,
      maxWordsPerLine: 3,
      glow: true,
    ),
    'Poster Ink' => const CaptionDesign(
      size: 31,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFD8FF40),
      weight: FontWeight.w900,
      effect: CaptionEffect.pop,
      font: CaptionFont.permanentMarker,
      outlineWidth: 2.2,
      maxWordsPerLine: 3,
      layout: CaptionLayout.ladder,
      uppercase: true,
    ),
    'Block Parade' => const CaptionDesign(
      size: 29,
      position: CaptionPosition.center,
      color: Color(0xFFFFF8E7),
      activeColor: Color(0xFFFF794D),
      weight: FontWeight.w900,
      effect: CaptionEffect.bounce,
      font: CaptionFont.bungee,
      outlineWidth: 1.8,
      maxWordsPerLine: 3,
      uppercase: true,
    ),
    'Prism Grotesk' => const CaptionDesign(
      size: 30,
      position: CaptionPosition.center,
      color: Color(0xFF8EEBFF),
      activeColor: Color(0xFFFF86E6),
      weight: FontWeight.w800,
      effect: CaptionEffect.drift,
      font: CaptionFont.spaceGrotesk,
      outlineWidth: 1.2,
      maxWordsPerLine: 3,
      doubleLayer: true,
      glow: true,
    ),
    'Arcade Pulse' => const CaptionDesign(
      size: 17,
      position: CaptionPosition.center,
      color: Color(0xFFD8FF51),
      activeColor: Color(0xFFD787FF),
      weight: FontWeight.w800,
      effect: CaptionEffect.pulse,
      font: CaptionFont.pixel,
      outlineWidth: 0,
      maxWordsPerLine: 3,
      uppercase: true,
      glow: true,
    ),
    'Luxe Title' => const CaptionDesign(
      size: 35,
      position: CaptionPosition.center,
      color: Color(0xFFFFEDD1),
      activeColor: Color(0xFFFF78AE),
      weight: FontWeight.w600,
      effect: CaptionEffect.fade,
      font: CaptionFont.abril,
      outlineWidth: 0,
      maxWordsPerLine: 2,
      layout: CaptionLayout.hierarchy,
      glow: true,
    ),
    'Velvet Script' => const CaptionDesign(
      size: 37,
      position: CaptionPosition.center,
      color: Color(0xFFFFD6EC),
      activeColor: Colors.white,
      weight: FontWeight.w700,
      effect: CaptionEffect.slideUp,
      font: CaptionFont.lobster,
      outlineWidth: 1.4,
      maxWordsPerLine: 2,
      glow: true,
    ),
    'Classic Cut' => const CaptionDesign(
      size: 34,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFFF634F),
      weight: FontWeight.w800,
      effect: CaptionEffect.stagger,
      font: CaptionFont.oswald,
      outlineWidth: 2.4,
      maxWordsPerLine: 3,
      layout: CaptionLayout.ladder,
      uppercase: true,
    ),
    'Reel Candy' => const CaptionDesign(
      size: 30,
      position: CaptionPosition.center,
      color: Color(0xFF63EEFF),
      activeColor: Color(0xFFFFE96C),
      weight: FontWeight.w800,
      effect: CaptionEffect.bounce,
      font: CaptionFont.righteous,
      outlineWidth: 2,
      maxWordsPerLine: 3,
      doubleLayer: true,
    ),
    'Blackout Bold' => const CaptionDesign(
      size: 29,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFB9FF47),
      weight: FontWeight.w900,
      effect: CaptionEffect.pop,
      font: CaptionFont.archivoBlack,
      backgroundColor: Color(0xE0000000),
      boxHorizontalPadding: 13,
      boxVerticalPadding: 8,
      boxRadius: 3,
      outlineWidth: 0,
      maxWordsPerLine: 3,
      uppercase: true,
    ),
    'Pixel Snap' => const CaptionDesign(
      size: 21,
      position: CaptionPosition.center,
      color: Color(0xFFF6F6F6),
      activeColor: Color(0xFFFF6A84),
      weight: FontWeight.w800,
      effect: CaptionEffect.stagger,
      font: CaptionFont.rubikMono,
      outlineWidth: 1.4,
      maxWordsPerLine: 3,
      uppercase: true,
    ),
    'Sunbeam Serif' => const CaptionDesign(
      size: 33,
      position: CaptionPosition.center,
      color: Color(0xFFFFF6C9),
      activeColor: Color(0xFFFF9F45),
      weight: FontWeight.w700,
      effect: CaptionEffect.pulse,
      font: CaptionFont.playfair,
      outlineWidth: 1.3,
      maxWordsPerLine: 3,
      glow: true,
    ),
    'Doodle Yellow' => const CaptionDesign(
      size: 32,
      position: CaptionPosition.center,
      color: Color(0xFFFFE755),
      activeColor: Colors.white,
      weight: FontWeight.w900,
      effect: CaptionEffect.bounce,
      font: CaptionFont.permanentMarker,
      outlineWidth: 2.5,
      maxWordsPerLine: 3,
      layout: CaptionLayout.ladder,
    ),
    'Bubble Chrome' => const CaptionDesign(
      size: 28,
      position: CaptionPosition.center,
      color: Color(0xFFBCEFFF),
      activeColor: Colors.white,
      weight: FontWeight.w900,
      effect: CaptionEffect.pop,
      font: CaptionFont.bungee,
      outlineWidth: 2.1,
      maxWordsPerLine: 2,
      doubleLayer: true,
      uppercase: true,
    ),
    'Clean Digital' => const CaptionDesign(
      size: 29,
      position: CaptionPosition.center,
      color: Color(0xFFEEFFF8),
      activeColor: Color(0xFF71FFB2),
      weight: FontWeight.w700,
      effect: CaptionEffect.typewriter,
      font: CaptionFont.spaceGrotesk,
      letterSpacing: .35,
      outlineWidth: 0,
      maxWordsPerLine: 4,
    ),
    'Film Noir' => const CaptionDesign(
      size: 32,
      position: CaptionPosition.center,
      color: Color(0xFFFFF4D6),
      activeColor: Color(0xFFFF5D5D),
      weight: FontWeight.w700,
      effect: CaptionEffect.slideUp,
      font: CaptionFont.oswald,
      outlineWidth: 2,
      maxWordsPerLine: 3,
      layout: CaptionLayout.hierarchy,
      uppercase: true,
    ),
    'Sunset Script' => const CaptionDesign(
      size: 40,
      position: CaptionPosition.center,
      color: Color(0xFFFFD19B),
      activeColor: Color(0xFFFF6B9D),
      weight: FontWeight.w700,
      effect: CaptionEffect.drift,
      font: CaptionFont.caveat,
      outlineWidth: 1.2,
      maxWordsPerLine: 3,
      glow: true,
    ),
    'Viva Poster' => const CaptionDesign(
      size: 34,
      position: CaptionPosition.center,
      color: Color(0xFFFFD7F0),
      activeColor: Color(0xFFFFEF78),
      weight: FontWeight.w600,
      effect: CaptionEffect.pop,
      font: CaptionFont.abril,
      outlineWidth: 1.1,
      maxWordsPerLine: 2,
      layout: CaptionLayout.hierarchy,
    ),
    'Soda Pop' => const CaptionDesign(
      size: 30,
      position: CaptionPosition.center,
      color: Color(0xFFFFAEE2),
      activeColor: Color(0xFF7AE5FF),
      weight: FontWeight.w800,
      effect: CaptionEffect.bounce,
      font: CaptionFont.righteous,
      outlineWidth: 2,
      maxWordsPerLine: 3,
      doubleLayer: true,
    ),
    'Urban Mono' => const CaptionDesign(
      size: 20,
      position: CaptionPosition.center,
      color: Color(0xFFEAEAEA),
      activeColor: Color(0xFFFFAC4D),
      weight: FontWeight.w800,
      effect: CaptionEffect.stagger,
      font: CaptionFont.rubikMono,
      outlineWidth: 1.1,
      maxWordsPerLine: 3,
      uppercase: true,
    ),
    'Chrome Marker' => const CaptionDesign(
      size: 31,
      position: CaptionPosition.center,
      color: Color(0xFFF6F6F6),
      activeColor: Color(0xFF9DE2FF),
      weight: FontWeight.w900,
      effect: CaptionEffect.drift,
      font: CaptionFont.permanentMarker,
      outlineWidth: 2.2,
      maxWordsPerLine: 3,
      doubleLayer: true,
    ),
    'Neon Serif' => const CaptionDesign(
      size: 33,
      position: CaptionPosition.center,
      color: Color(0xFFEAC9FF),
      activeColor: Color(0xFF72FAFF),
      weight: FontWeight.w700,
      effect: CaptionEffect.pulse,
      font: CaptionFont.playfair,
      outlineWidth: 1.5,
      maxWordsPerLine: 3,
      glow: true,
    ),
    'Storybook Script' => const CaptionDesign(
      size: 38,
      position: CaptionPosition.center,
      color: Color(0xFFFFE3BA),
      activeColor: Color(0xFFEAA8FF),
      weight: FontWeight.w700,
      effect: CaptionEffect.fade,
      font: CaptionFont.lobster,
      outlineWidth: 1.2,
      maxWordsPerLine: 2,
      glow: true,
    ),
    'Punchline Sans' => const CaptionDesign(
      size: 29,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFFFD449),
      weight: FontWeight.w900,
      effect: CaptionEffect.stagger,
      font: CaptionFont.bungee,
      outlineWidth: 2.4,
      maxWordsPerLine: 3,
      layout: CaptionLayout.ladder,
      uppercase: true,
    ),
    'Warm Stage' => const CaptionDesign(
      size: 30,
      position: CaptionPosition.center,
      color: Colors.white,
      activeColor: Color(0xFFFFC857),
      weight: FontWeight.w900,
      effect: CaptionEffect.pop,
      font: CaptionFont.montserrat,
      outlineWidth: 2.2,
      maxWordsPerLine: 3,
      uppercase: true,
      hardShadow: true,
    ),
    'Blink Pop' => const CaptionDesign(
      size: 30,
      color: Colors.white,
      activeColor: Color(0xFFC96442),
      weight: FontWeight.w800,
      effect: CaptionEffect.pop,
      font: CaptionFont.poppins,
      outlineWidth: 2,
      maxWordsPerLine: 4,
    ),
    'Karaoke Fill' => const CaptionDesign(
      size: 28,
      color: Colors.white,
      activeColor: Color(0xFFCF6C4F),
      weight: FontWeight.w900,
      effect: CaptionEffect.karaoke,
      font: CaptionFont.inter,
      outlineWidth: 1.5,
      maxWordsPerLine: 4,
    ),
    'Bold Box' => const CaptionDesign(
      size: 31,
      color: Colors.white,
      activeColor: Color(0xFFFFD166),
      weight: FontWeight.w800,
      effect: CaptionEffect.fade,
      font: CaptionFont.anton,
      backgroundColor: Color(0xD9000000),
      boxHorizontalPadding: 14,
      boxVerticalPadding: 9,
      boxRadius: 10,
      outlineWidth: 0,
      maxWordsPerLine: 3,
    ),
    'Minimal Clean' => const CaptionDesign(
      size: 23,
      color: Color(0xFFE5E5E5),
      activeColor: Color(0xFFFFE600),
      weight: FontWeight.w500,
      effect: CaptionEffect.fade,
      font: CaptionFont.inter,
      letterSpacing: .2,
      outlineWidth: 0,
      maxWordsPerLine: 5,
    ),
    'Neon Glow' => const CaptionDesign(
      size: 28,
      color: Color(0xFF39FF88),
      activeColor: Colors.white,
      weight: FontWeight.w700,
      effect: CaptionEffect.pop,
      font: CaptionFont.poppins,
      position: CaptionPosition.center,
      outlineWidth: 0,
      maxWordsPerLine: 3,
      glow: true,
    ),
    'Typewriter' => const CaptionDesign(
      size: 24,
      color: Colors.white,
      activeColor: Color(0xFFC96442),
      weight: FontWeight.w700,
      effect: CaptionEffect.typewriter,
      font: CaptionFont.jetBrainsMono,
      letterSpacing: .6,
      outlineWidth: 0,
      maxWordsPerLine: 4,
    ),
    'Bounce' => const CaptionDesign(
      size: 30,
      color: Colors.white,
      activeColor: Color(0xFFFFD166),
      weight: FontWeight.w800,
      effect: CaptionEffect.bounce,
      font: CaptionFont.baloo2,
      outlineWidth: 1,
      maxWordsPerLine: 4,
    ),
    'Podcast Clean' => const CaptionDesign(
      size: 22,
      color: Colors.white,
      activeColor: Color(0xFFCF6C4F),
      weight: FontWeight.w700,
      effect: CaptionEffect.slideUp,
      font: CaptionFont.dmSans,
      backgroundColor: Color(0xD91A1A2E),
      boxHorizontalPadding: 14,
      boxVerticalPadding: 8,
      boxRadius: 100,
      outlineWidth: 0,
      maxWordsPerLine: 4,
    ),
    _ => const CaptionDesign(
      size: 30,
      color: Colors.white,
      activeColor: Color(0xFFC96442),
      weight: FontWeight.w800,
      effect: CaptionEffect.pop,
      font: CaptionFont.poppins,
      outlineWidth: 2,
      maxWordsPerLine: 4,
    ),
  };
}
