name: Flutter Web Deploy to Netlify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --web-renderer html

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: |
          netlify deploy --site="d0777a7c-1bcb-41bd-a7ad-d48216d804ba" --auth="nfp_fvfdrGwUNtJPNu3QHXn8MqqckU1ZgWat37f5" --dir=build/web --prod --json
